[package]
name = "flight"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { git = "ssh://git@github-research.gatech.edu/YJSP/common", features = ["sequences"] }
dns-lookup = "2.0.4"
jeflog = "0.1.0"
postcard = { version = "1.0.8", features = ["alloc"] }